"""add tasks attendance member-fields series

Revision ID: 4346392a4618
Revises: 0002
Create Date: 2026-10-05 23:00:03.493563
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.core.database

revision: str = "4346392a4618"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_tasks",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column(
            "icon",
            sa.Enum(
                "laundry",
                "ball",
                "water",
                "car",
                "flag",
                "key",
                "shirt",
                "food",
                "medkit",
                "other",
                name="ck_taskicon",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", app.core.database.UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", app.core.database.UtcDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "icon IN ('laundry', 'ball', 'water', 'car', 'flag',"
            " 'key', 'shirt', 'food', 'medkit', 'other')",
            name="ck_taskicon",
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "name", name="uq_team_tasks_team_name"),
    )
    with op.batch_alter_table("team_tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_team_tasks_team_id"), ["team_id"], unique=False)

    op.create_table(
        "task_assignments",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("team_task_id", sa.Uuid(), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", app.core.database.UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", app.core.database.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["member_id"], ["members.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_task_id"], ["team_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "event_id", "team_task_id", "member_id", name="uq_task_assignments_event_task_member"
        ),
    )
    with op.batch_alter_table("task_assignments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_task_assignments_event_id"), ["event_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_task_assignments_member_id"), ["member_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_task_assignments_team_task_id"), ["team_task_id"], unique=False
        )

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("series_id", sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f("ix_events_series_id"), ["series_id"], unique=False)

    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "attendance",
                sa.Enum(
                    "on_time",
                    "late",
                    "excused",
                    "unexcused",
                    "injured",
                    name="ck_attendancestatus",
                    native_enum=False,
                    create_constraint=True,
                    length=20,
                ),
                nullable=True,
            )
        )

    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.add_column(sa.Column("phone", sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column("birth_date", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("license_number", sa.String(length=30), nullable=True))
        batch_op.add_column(
            sa.Column(
                "jersey_size",
                sa.Enum(
                    "6y",
                    "8y",
                    "10y",
                    "12y",
                    "14y",
                    "xs",
                    "s",
                    "m",
                    "l",
                    "xl",
                    "xxl",
                    name="ck_jerseysize",
                    native_enum=False,
                    create_constraint=True,
                    length=20,
                ),
                nullable=True,
            )
        )
        batch_op.create_index(batch_op.f("ix_members_last_name"), ["last_name"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_members_last_name"))
        batch_op.drop_column("jersey_size")
        batch_op.drop_column("license_number")
        batch_op.drop_column("birth_date")
        batch_op.drop_column("phone")

    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.drop_column("attendance")

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_series_id"))
        batch_op.drop_column("series_id")

    with op.batch_alter_table("task_assignments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_assignments_team_task_id"))
        batch_op.drop_index(batch_op.f("ix_task_assignments_member_id"))
        batch_op.drop_index(batch_op.f("ix_task_assignments_event_id"))

    op.drop_table("task_assignments")
    with op.batch_alter_table("team_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_team_tasks_team_id"))

    op.drop_table("team_tasks")
    # ### end Alembic commands ###
